# -*- coding: utf-8 -*-
"""24-09-02-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0i6acO1bOv2wmxDB2U_BXdYIYZSZkHe
"""

print("이번학기에도 무언가 새로운 것을 배워 봅시다")

# many power mode 는 조심해서 사용하세요
# no power mode 에서도 불꽃 코딩이 가능할까요?
# 중간정도의 힘으로 코드를 잘 만들어 봅시다